services:
  db:
    image: postgres:15-alpine
    container_name: orders_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: orders_db
      POSTGRES_HOST_AUTH_METHOD: trust  # используется для тестирования
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build: .
    container_name: orders_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres@db:5432/orders_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./config.py:/app/config.py
      - ./setting.yaml:/app/setting.yaml
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

volumes:
  postgres_data:
